### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by myran2** [myran2/BrickBreaker#1]
- [x] Entities Class
  - Stores stuff like sdl_texture, position on screen
  - Entities like ball, paddle, brick will extend this class
- [x] Menus
  - Play game
  - Anything else?
  - Options
- [x] ~~Options~~ No Time
  - ~~Config file/Config loading system~~
- [x] Physics?
  - Making the ball bounce and stuff
- [x] Powerups
  - How should we implement those, gameplay wise?
- [x] Logging System
  - Could be useful for debugging
- [x] ~~Animations~~ No Time
- [x] Makefile
- [x] Audio
- [x] Maps/Map Loading
