### ISSUE TITLE
New Todo

### ISSUE THREAD

**Issue by myran2** [myran2/BrickBreaker#2]
- [x] Finish bricks
  - ~~Display~~
  - ~~Die when hit~~
  - ~~Play collision sound~~
- [x] Improve game over screen
  - add final score
- [x] Handle when someone wins the level
  - reset bricks
  - reset paddle pos.
- [x] Drop powerup/powerdown when user presses space

3 lives per whole game
- [x] Winning screen:
  - You Win!
  - Show final score
- [x] Fix memory leak related to background.
- [x] Maybe: Credits page!
- [x] Definitely: How to play Page!
